//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarEventCalendar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarEventCalendar.FormResource", typeof(FormResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất sự kiện từ ngày âm.
        /// </summary>
        internal static string Form_FinishConvertDlgTitle {
            get {
                return ResourceManager.GetString("Form_FinishConvertDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xuất file thành công. Có thể lấy file nhập vào Outlook hoặc Google Calendar.
        /// </summary>
        internal static string Form_FinishConvertMsg {
            get {
                return ResourceManager.GetString("Form_FinishConvertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLIC.
        /// </summary>
        internal static string iCal_Class {
            get {
                return ResourceManager.GetString("iCal_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string iCal_DefaultFolder {
            get {
                return ResourceManager.GetString("iCal_DefaultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Âm Lịch:.
        /// </summary>
        internal static string iCal_DescNgayAmLich {
            get {
                return ResourceManager.GetString("iCal_DescNgayAmLich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Dương Lịch:.
        /// </summary>
        internal static string iCal_DescNgayDuongLich {
            get {
                return ResourceManager.GetString("iCal_DescNgayDuongLich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEVENT.
        /// </summary>
        internal static string iCal_EventName {
            get {
                return ResourceManager.GetString("iCal_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} AL).
        /// </summary>
        internal static string iCal_EventTitleFormat {
            get {
                return ResourceManager.GetString("iCal_EventTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}/{2} AL: {3}.
        /// </summary>
        internal static string iCal_EventToStringFormat {
            get {
                return ResourceManager.GetString("iCal_EventToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NgayNghiNho_{0}-{1}.ics.
        /// </summary>
        internal static string iCal_FileNameFormat {
            get {
                return ResourceManager.GetString("iCal_FileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có địa điểm.
        /// </summary>
        internal static string iCal_Location {
            get {
                return ResourceManager.GetString("iCal_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUBLISH.
        /// </summary>
        internal static string iCal_Method {
            get {
                return ResourceManager.GetString("iCal_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyen Hoang Minh/www.nguyenhoangminh.info/Lunar Calendar Convert and Generator.
        /// </summary>
        internal static string iCal_ProdId {
            get {
                return ResourceManager.GetString("iCal_ProdId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((?&lt;day&gt;(\d{1,2}))/(?&lt;month&gt;(\d{1,2}))): (?&lt;event&gt;([\w\d\s]*)).
        /// </summary>
        internal static string Process_InputRegEx {
            get {
                return ResourceManager.GetString("Process_InputRegEx", resourceCulture);
            }
        }
    }
}
